### ISSUE TITLE
No Tab?

### ISSUE THREAD

**Issue by kyle-aoki** [hereafter/dotNotepad#1]
Why is there no tab functionality on this application? For a paid app, this is unacceptable.

**Comment by hereafter** [comment]
this is just an app to recreate classical windows notepad in modern API. 
so it currently sticks to this goal

**Comment by hereafter** [comment]
My bad you meant "Tab" key, working on a fix

**Comment by hereafter** [comment]
a fix in on its way, update 1.6.368 should fix this issue

**Comment by hereafter** [comment]
please verify

**Comment by kyle-aoki** [comment]
nice! tab works now. thank you
